/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProviderProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'pricePerHour' : IDL.Nat,
  'isActive' : IDL.Bool,
  'availability' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const Pet = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'breed' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'requestedDate' : IDL.Text,
  'petId' : IDL.Nat,
  'petParent' : IDL.Principal,
  'providerId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPet' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createProviderProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deletePet' : IDL.Func([IDL.Nat], [], []),
  'getCallerProviderProfile' : IDL.Func(
      [],
      [IDL.Opt(ProviderProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProviderProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProviderProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
  'listCallerPets' : IDL.Func([], [IDL.Vec(Pet)], ['query']),
  'listMyBookingsAsPetParent' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listMyBookingsAsProvider' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listProvidersByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'toggleProviderActive' : IDL.Func([IDL.Principal], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePet' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateProviderProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProviderProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'pricePerHour' : IDL.Nat,
    'isActive' : IDL.Bool,
    'availability' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const Pet = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'breed' : IDL.Text,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'requestedDate' : IDL.Text,
    'petId' : IDL.Nat,
    'petParent' : IDL.Principal,
    'providerId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPet' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createProviderProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deletePet' : IDL.Func([IDL.Nat], [], []),
    'getCallerProviderProfile' : IDL.Func(
        [],
        [IDL.Opt(ProviderProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProviderProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProviderProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
    'listCallerPets' : IDL.Func([], [IDL.Vec(Pet)], ['query']),
    'listMyBookingsAsPetParent' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listMyBookingsAsProvider' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listProvidersByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'toggleProviderActive' : IDL.Func([IDL.Principal], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePet' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateProviderProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };