/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'notes' : string,
  'requestedDate' : string,
  'petId' : bigint,
  'petParent' : Principal,
  'providerId' : Principal,
}
export interface Pet {
  'id' : bigint,
  'age' : bigint,
  'owner' : Principal,
  'name' : string,
  'notes' : string,
  'breed' : string,
}
export interface ProviderProfile {
  'bio' : string,
  'displayName' : string,
  'owner' : Principal,
  'city' : string,
  'pricePerHour' : bigint,
  'isActive' : boolean,
  'availability' : string,
  'category' : string,
  'rating' : bigint,
  'reviewCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPet' : ActorMethod<[string, string, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[Principal, bigint, string, string], undefined>,
  'createProviderProfile' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
  'deletePet' : ActorMethod<[bigint], undefined>,
  'getCallerProviderProfile' : ActorMethod<[], [] | [ProviderProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProviderProfile' : ActorMethod<[Principal], [] | [ProviderProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'listCallerPets' : ActorMethod<[], Array<Pet>>,
  'listMyBookingsAsPetParent' : ActorMethod<[], Array<Booking>>,
  'listMyBookingsAsProvider' : ActorMethod<[], Array<Booking>>,
  'listProvidersByCategory' : ActorMethod<[string], Array<ProviderProfile>>,
  'submitReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'toggleProviderActive' : ActorMethod<[Principal], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'updatePet' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'updateProviderProfile' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];